name: "Hello World Workflow"

# control when the action will run. Triggers the workflow on push done to master or production branch

on:    #on key is used as events
  push:
    branches:    #somebody push anything on master/production branch then this workflow will be executed.
      - master
      - production

jobs:  # it will be configure what job to be done 
  hello_world: #name of the jobs key
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World" # Name of the steps
        run: echo "Hello World"  # What is done in steps
      