name: "Multi Event Pipline / Workflow"

on:
    push:
        branches:
            - master

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master push"
              run: echo "Running on master push"
            
            - name: "Date of Execution"
              run: date
              

